import arcade
from enum import Enum

class Key(Enum):
    # Letter keys.
    A = arcade.key.A
    B = arcade.key.B
    C = arcade.key.C
    D = arcade.key.D
    E = arcade.key.E
    F = arcade.key.F
    G = arcade.key.G
    H = arcade.key.H
    I = arcade.key.I
    J = arcade.key.J
    K = arcade.key.K
    L = arcade.key.L
    M = arcade.key.M
    N = arcade.key.N
    O = arcade.key.O
    P = arcade.key.P
    Q = arcade.key.Q
    R = arcade.key.R
    S = arcade.key.S
    T = arcade.key.T
    U = arcade.key.U
    V = arcade.key.V
    W = arcade.key.W
    X = arcade.key.X
    Y = arcade.key.Y
    Z = arcade.key.Z

    # Number keys.
    ZERO = arcade.key.ZERO
    ONE = arcade.key.ONE
    TWO = arcade.key.TWO
    THREE = arcade.key.THREE
    FOUR = arcade.key.FOUR
    FIVE = arcade.key.FIVE
    SIX = arcade.key.SIX
    SEVEN = arcade.key.SEVEN
    EIGHT = arcade.key.EIGHT
    NINE = arcade.key.NINE

    # Symbol keys.
    SPACE = arcade.key.SPACE
    ENTER = arcade.key.ENTER
    BACKSPACE = arcade.key.BACKSPACE
    TAB = arcade.key.TAB
    ESCAPE = arcade.key.ESCAPE
    LEFT = arcade.key.LEFT
    UP = arcade.key.UP
    RIGHT = arcade.key.RIGHT
    DOWN = arcade.key.DOWN
    SHIFT = arcade.key.LSHIFT
    CONTROL = arcade.key.LCTRL
    ALT = arcade.key.LALT
    CAPS_LOCK = arcade.key.CAPSLOCK
    F1 = arcade.key.F1
    F2 = arcade.key.F2
    F3 = arcade.key.F3
    F4 = arcade.key.F4
    F5 = arcade.key.F5
    F6 = arcade.key.F6
    F7 = arcade.key.F7
    F8 = arcade.key.F8
    F9 = arcade.key.F9
    F10 = arcade.key.F10
    F11 = arcade.key.F11
    F12 = arcade.key.F12